### ISSUE TITLE
Exception on startup (Android 6.0)

### ISSUE THREAD

**Issue by yenon** [restorer/gloomy-dungeons-2#8]
I just started the app for the first time on Android 6.
This exeption occured immediately, nothing was shown.

**Comment by yenon** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.zamedev.gloomydungeons2.opensource/zame.game.MainActivity}: android.view.InflateException: Binary XML file line #40: Error inflating class com.android.internal.widget.ActionBarView

at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)

at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)

at android.app.ActivityThread.-wrap11(ActivityThread.java)

at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)

at android.os.Handler.dispatchMessage(Handler.java:102)

at android.os.Looper.loop(Looper.java:148)

at android.app.ActivityThread.main(ActivityThread.java:5461)

at java.lang.reflect.Method.invoke(Native Method)

at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

Caused by: android.view.InflateException: Binary XML file line #40: Error inflating class com.android.internal.widget.ActionBarView

at org.holoeverywhere.LayoutInflater._createView(Unknown Source)

at org.holoeverywhere.LayoutInflater.onCreateView(Unknown Source)

at org.holoeverywhere.LayoutInflater.createViewFromTag(Unknown Source)

at org.holoeverywhere.LayoutInflater.rInflate(Unknown Source)

at org.holoeverywhere.LayoutInflater.rInflate(Unknown Source)

at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)

at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)

at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)

at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:4169)

at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4241)

at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:463)

at android.app.Activity.setContentView(Activity.java:2208)

at android.support.v7.a.b.superSetContentView(Unknown Source)

at android.support.v7.a.f.a(Unknown Source)

at android.support.v7.a.b.setContentView(Unknown Source)

at android.support.v4.app._HoloActivity.access$201(Unknown Source)

at android.support.v4.app._HoloActivity$1.justPost(Unknown Source)

at org.holoeverywhere.addon.IAddonAttacher$AddonCallback.post(Unknown Source)

at org.holoeverywhere.addon.IAddonBasicAttacher.performAddonAction(Unknown Source)

at org.holoeverywhere.app.Activity.performAddonAction(Unknown Source)

at android.support.v4.app._HoloActivity.requestDecorView(Unknown Source)

at android.support.v4.app._HoloActivity.setContentView(Unknown Source)

at zame.game.MainActivity.onCreate(Unknown Source)

at android.app.Activity.performCreate(Activity.java:6251)

at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)

at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)

at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)

at android.app.ActivityThread.-wrap11(ActivityThread.java)

at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)

at android.os.Handler.dispatchMessage(Handler.java:102)

at android.os.Looper.loop(Looper.java:148)

at android.app.ActivityThread.main(ActivityThread.java:5461)

at java.lang.reflect.Method.invoke(Native Method)

at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

Caused by: java.lang.reflect.InvocationTargetException

at java.lang.reflect.Constructor.newInstance(Native Method)

at org.holoeverywhere.LayoutInflater._createView(Unknown Source)

at org.holoeverywhere.LayoutInflater.onCreateView(Unknown Source)

at org.holoeverywhere.LayoutInflater.createViewFromTag(Unknown Source)

at org.holoeverywhere.LayoutInflater.rInflate(Unknown Source)

at org.holoeverywhere.LayoutInflater.rInflate(Unknown Source)

at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)

at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)

at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)

at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:4169)

at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4241)

at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:463)

at android.app.Activity.setContentView(Activity.java:2208)

at android.support.v7.a.b.superSetContentView(Unknown Source)

at android.support.v7.a.f.a(Unknown Source)

at android.support.v7.a.b.setContentView(Unknown Source)

at android.support.v4.app._HoloActivity.access$201(Unknown Source)

at android.support.v4.app._HoloActivity$1.justPost(Unknown Source)

at org.holoeverywhere.addon.IAddonAttacher$AddonCallback.post(Unknown Source)

at org.holoeverywhere.addon.IAddonBasicAttacher.performAddonAction(Unknown Source)

at org.holoeverywhere.app.Activity.performAddonAction(Unknown Source)

at android.support.v4.app._HoloActivity.requestDecorView(Unknown Source)

at android.support.v4.app._HoloActivity.setContentView(Unknown Source)

at zame.game.MainActivity.onCreate(Unknown Source)

at android.app.Activity.performCreate(Activity.java:6251)

at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)

at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)

at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)

at android.app.ActivityThread.-wrap11(ActivityThread.java)

at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)

at android.os.Handler.dispatchMessage(Handler.java:102)

at android.os.Looper.loop(Looper.java:148)

at android.app.ActivityThread.main(ActivityThread.java:5461)

at java.lang.reflect.Method.invoke(Native Method)

at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

Caused by: java.lang.IllegalStateException: Could not find font in raw resources: roboto_medium

at org.holoeverywhere.FontLoader$RawLazyFont.setRawResourceId(Unknown Source)

at org.holoeverywhere.FontLoader$RawLazyFont.loadTypeface(Unknown Source)

at org.holoeverywhere.FontLoader$Font.getTypeface(Unknown Source)

at org.holoeverywhere.FontLoader$FontCollector.getTypeface(Unknown Source)

at org.holoeverywhere.FontLoader$FontCollector.getTypeface(Unknown Source)

at zame.game.misc.d.getTypeface(Unknown Source)

at org.holoeverywhere.FontLoader.applyInternal(Unknown Source)

at org.holoeverywhere.FontLoader.apply(Unknown Source)

at org.holoeverywhere.FontLoader.applyDefaultFont(Unknown Source)

at org.holoeverywhere.widget.TextView.setFontStyle(Unknown Source)

at org.holoeverywhere.widget.TextView.setFontStyle(Unknown Source)

at org.holoeverywhere.widget.TextView.setTextAppearance(Unknown Source)

at org.holoeverywhere.widget.TextView.setTextAppearance(Unknown Source)

at org.holoeverywhere.widget.TextView.setTextAppearance(Unknown Source)

at android.widget.TextView.setTextAppearance(TextView.java:2738)

at com.android.internal.widget.ActionBarView.initTitle(ActionBarView.java:816)

at com.android.internal.widget.ActionBarView.setDisplayOptions(ActionBarView.java:622)

at com.android.internal.widget.ActionBarView.<init>(ActionBarView.java:206)

at java.lang.reflect.Constructor.newInstance(Native Method)

at org.holoeverywhere.LayoutInflater._createView(Unknown Source)

at org.holoeverywhere.LayoutInflater.onCreateView(Unknown Source)

at org.holoeverywhere.LayoutInflater.createViewFromTag(Unknown Source)

at org.holoeverywhere.LayoutInflater.rInflate(Unknown Source)

at org.holoeverywhere.LayoutInflater.rInflate(Unknown Source)

at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)

at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)

at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)

at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:4169)

at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4241)

at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:463)

at android.app.Activity.setContentView(Activity.java:2208)

at android.support.v7.a.b.superSetContentView(Unknown Source)

at android.support.v7.a.f.a(Unknown Source)

at android.support.v7.a.b.setContentView(Unknown Source)

at android.support.v4.app._HoloActivity.access$201(Unknown Source)

at android.support.v4.app._HoloActivity$1.justPost(Unknown Source)

at org.holoeverywhere.addon.IAddonAttacher$AddonCallback.post(Unknown Source)

at org.holoeverywhere.addon.IAddonBasicAttacher.performAddonAction(Unknown Source)

at org.holoeverywhere.app.Activity.performAddonAction(Unknown Source)

at android.support.v4.app._HoloActivity.requestDecorView(Unknown Source)

at android.support.v4.app._HoloActivity.setContentView(Unknown Source)

at zame.game.MainActivity.onCreate(Unknown Source)

at android.app.Activity.performCreate(Activity.java:6251)

at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)

at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)

at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)

at android.app.ActivityThread.-wrap11(ActivityThread.java)

at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)

at android.os.Handler.dispatchMessage(Handler.java:102)

at android.os.Looper.loop(Looper.java:148)

at android.app.ActivityThread.main(ActivityThread.java:5461)

at java.lang.reflect.Method.invoke(Native Method)

at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

**Comment by yenon** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.zamedev.gloomydungeons2.opensource/zame.game.MainActivity}: android.view.InflateException: Binary XML file line #40: Error inflating class com.android.internal.widget.ActionBarView
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5461)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
Caused by: android.view.InflateException: Binary XML file line #40: Error inflating class com.android.internal.widget.ActionBarView
    at org.holoeverywhere.LayoutInflater._createView(Unknown Source)
    at org.holoeverywhere.LayoutInflater.onCreateView(Unknown Source)
    at org.holoeverywhere.LayoutInflater.createViewFromTag(Unknown Source)
    at org.holoeverywhere.LayoutInflater.rInflate(Unknown Source)
    at org.holoeverywhere.LayoutInflater.rInflate(Unknown Source)
    at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)
    at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)
    at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)
    at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:4169)
    at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4241)
    at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:463)
    at android.app.Activity.setContentView(Activity.java:2208)
    at android.support.v7.a.b.superSetContentView(Unknown Source)
    at android.support.v7.a.f.a(Unknown Source)
    at android.support.v7.a.b.setContentView(Unknown Source)
    at android.support.v4.app._HoloActivity.access$201(Unknown Source)
    at android.support.v4.app._HoloActivity$1.justPost(Unknown Source)
    at org.holoeverywhere.addon.IAddonAttacher$AddonCallback.post(Unknown Source)
    at org.holoeverywhere.addon.IAddonBasicAttacher.performAddonAction(Unknown Source)
    at org.holoeverywhere.app.Activity.performAddonAction(Unknown Source)
    at android.support.v4.app._HoloActivity.requestDecorView(Unknown Source)
    at android.support.v4.app._HoloActivity.setContentView(Unknown Source)
    at zame.game.MainActivity.onCreate(Unknown Source)
    at android.app.Activity.performCreate(Activity.java:6251)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5461)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at org.holoeverywhere.LayoutInflater._createView(Unknown Source)
    at org.holoeverywhere.LayoutInflater.onCreateView(Unknown Source)
    at org.holoeverywhere.LayoutInflater.createViewFromTag(Unknown Source)
    at org.holoeverywhere.LayoutInflater.rInflate(Unknown Source)
    at org.holoeverywhere.LayoutInflater.rInflate(Unknown Source)
    at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)
    at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)
    at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)
    at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:4169)
    at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4241)
    at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:463)
    at android.app.Activity.setContentView(Activity.java:2208)
    at android.support.v7.a.b.superSetContentView(Unknown Source)
    at android.support.v7.a.f.a(Unknown Source)
    at android.support.v7.a.b.setContentView(Unknown Source)
    at android.support.v4.app._HoloActivity.access$201(Unknown Source)
    at android.support.v4.app._HoloActivity$1.justPost(Unknown Source)
    at org.holoeverywhere.addon.IAddonAttacher$AddonCallback.post(Unknown Source)
    at org.holoeverywhere.addon.IAddonBasicAttacher.performAddonAction(Unknown Source)
    at org.holoeverywhere.app.Activity.performAddonAction(Unknown Source)
    at android.support.v4.app._HoloActivity.requestDecorView(Unknown Source)
    at android.support.v4.app._HoloActivity.setContentView(Unknown Source)
    at zame.game.MainActivity.onCreate(Unknown Source)
    at android.app.Activity.performCreate(Activity.java:6251)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5461)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
Caused by: java.lang.IllegalStateException: Could not find font in raw resources: roboto_medium
    at org.holoeverywhere.FontLoader$RawLazyFont.setRawResourceId(Unknown Source)
    at org.holoeverywhere.FontLoader$RawLazyFont.loadTypeface(Unknown Source)
    at org.holoeverywhere.FontLoader$Font.getTypeface(Unknown Source)
    at org.holoeverywhere.FontLoader$FontCollector.getTypeface(Unknown Source)
    at org.holoeverywhere.FontLoader$FontCollector.getTypeface(Unknown Source)
    at zame.game.misc.d.getTypeface(Unknown Source)
    at org.holoeverywhere.FontLoader.applyInternal(Unknown Source)
    at org.holoeverywhere.FontLoader.apply(Unknown Source)
    at org.holoeverywhere.FontLoader.applyDefaultFont(Unknown Source)
    at org.holoeverywhere.widget.TextView.setFontStyle(Unknown Source)
    at org.holoeverywhere.widget.TextView.setFontStyle(Unknown Source)
    at org.holoeverywhere.widget.TextView.setTextAppearance(Unknown Source)
    at org.holoeverywhere.widget.TextView.setTextAppearance(Unknown Source)
    at org.holoeverywhere.widget.TextView.setTextAppearance(Unknown Source)
    at android.widget.TextView.setTextAppearance(TextView.java:2738)
    at com.android.internal.widget.ActionBarView.initTitle(ActionBarView.java:816)
    at com.android.internal.widget.ActionBarView.setDisplayOptions(ActionBarView.java:622)
    at com.android.internal.widget.ActionBarView.<init>(ActionBarView.java:206)
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at org.holoeverywhere.LayoutInflater._createView(Unknown Source)
    at org.holoeverywhere.LayoutInflater.onCreateView(Unknown Source)
    at org.holoeverywhere.LayoutInflater.createViewFromTag(Unknown Source)
    at org.holoeverywhere.LayoutInflater.rInflate(Unknown Source)
    at org.holoeverywhere.LayoutInflater.rInflate(Unknown Source)
    at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)
    at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)
    at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)
    at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:4169)
    at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4241)
    at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:463)
    at android.app.Activity.setContentView(Activity.java:2208)
    at android.support.v7.a.b.superSetContentView(Unknown Source)
    at android.support.v7.a.f.a(Unknown Source)
    at android.support.v7.a.b.setContentView(Unknown Source)
    at android.support.v4.app._HoloActivity.access$201(Unknown Source)
    at android.support.v4.app._HoloActivity$1.justPost(Unknown Source)
    at org.holoeverywhere.addon.IAddonAttacher$AddonCallback.post(Unknown Source)
    at org.holoeverywhere.addon.IAddonBasicAttacher.performAddonAction(Unknown Source)
    at org.holoeverywhere.app.Activity.performAddonAction(Unknown Source)
    at android.support.v4.app._HoloActivity.requestDecorView(Unknown Source)
    at android.support.v4.app._HoloActivity.setContentView(Unknown Source)
    at zame.game.MainActivity.onCreate(Unknown Source)
    at android.app.Activity.performCreate(Activity.java:6251)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5461)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

**Comment by restorer** [comment]
Is this happening with latest version? We already have commits that should fix it - https://github.com/restorer/gloomy-dungeons-2/commit/b798f9565d7ec0b37cc4a0e052b6f2ed4da720c9

**Comment by yenon** [comment]
Seems like the F-Droid repo is behind again.

**Comment by restorer** [comment]
Hmmm... Seems that f-droid has newest version.
I will try to run the game under Android 6.0 in a few days.

**Comment by restorer** [comment]
Okay, the game on F-Droid was updated few days ago (`org.zamedev.gloomydungeons2.opensource_1602221800.apk`).
- Real device (Samsung Galaxy Tab 2 10.1 with Cyanogenmod 6.0) - works!
- Emulator API 23 (6.0) - works!
- Emulator API 24 (6.X) - works!

**Comment by yenon** [comment]
I cannot confirm this. I'm testing on a real device aswell (LG G2 mini), running CM on Android 6.
Maybe arm-v7 is not supported by your app? If you need any information concerning my phone, feel free to ask.

**Comment by restorer** [comment]
Please install this unobfuscated version - http://pub.zame-dev.org/tmp/gd2-debug.apk

**Comment by restorer** [comment]
Any news?

**Comment by restorer** [comment]
No logcat from unobfuscated version - no fix.
